<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Critical Tables
    |--------------------------------------------------------------------------
    |
    | Tables listed here are considered "critical": they are snapshotted
    | before any destructive migration runs, and their contents are restored
    | automatically on rollback or via `migrate:fresh`.
    |
    | Add new tables here when they hold data that must not be lost.
    |
    */

    'critical_tables' => [
        'channels',
        'media_items',
        'playlists',
        'playlist_items',
        'schedule_templates',
        'schedule_blocks',
        'virtual_screens',
        'emission_state',
        'users',
    ],

    /*
    |--------------------------------------------------------------------------
    | Snapshot Path
    |--------------------------------------------------------------------------
    |
    | Directory where per-migration and release snapshots are stored.
    | Snapshots are intentionally outside `database/migrations/` so they
    | survive `migrate:fresh`, and they are gitignored by default.
    |
    */

    'snapshot_path' => 'database/snapshots',

    /*
    |--------------------------------------------------------------------------
    | Release Snapshot
    |--------------------------------------------------------------------------
    |
    | Filename (relative to snapshot_path) of the "production release" snapshot.
    | Generated by `php artisan db:export-production-data` and consumed by
    | `ProductionDataSeeder` after `migrate:fresh`.
    |
    */

    'release_snapshot' => 'release/production.json.gz',

    /*
    |--------------------------------------------------------------------------
    | Capture Chunk Size
    |--------------------------------------------------------------------------
    |
    | Number of rows streamed per chunk when capturing a table to JSON.gz.
    | Larger chunks are faster but use more memory. 5000 is a safe default
    | for tables with JSONB metadata up to ~10 KB per row.
    |
    */

    'chunk_size' => 5000,

    /*
    |--------------------------------------------------------------------------
    | FK Order
    |--------------------------------------------------------------------------
    |
    | Insert order for restore. Tables with no FK are appended automatically
    | by the snapshot service. Keep this list in dependency order: parents
    | before children.
    |
    */

    'fk_order' => [
        'users',
        'channels',
        'media_items',
        'playlists',
        'playlist_items',
        'schedule_templates',
        'schedule_blocks',
        'virtual_screens',
        'emission_state',
        'audit_logs',
    ],
];
